### ISSUE TITLE
The location of the sensor

### ISSUE THREAD

**Issue by SteinPanyu** [MadMax93/acc_sensor_rr-python#1]
Hello, 

I have a quick question. Do you know where the acc sesor is attached? say chest or wrist

Best regards and many thanks!

**Comment by MadMax93** [comment]
Hello SteinPanyu,

I attached my 3D-Acceleration sensor on the chest around the sternum. I hope that helps you. 

Greetings.

**Comment by SteinPanyu** [comment]
Thanks!
